services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - fintrack-net
      
  backend:
    build: ./be-fintrack-master
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - fintrack-net

  frontend:
    build:
      context: ./fe-fintrack-master
      args:
        - VITE_API_BASE_URL=http://backend:5000
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fintrack-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fintrack-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - fintrack-net

networks:
  fintrack-net:
    name: fintrack-net
